### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by francescofact** [reincubate/ricloud#16]
hi, i installed the python extension and cloned the repo, but when i run it with i get "invalid token"

`pi@raspberrypi:~/ricloud $ python -m ricloud f*******@****.it --password=*********

Push Api Error:
{
  "message": "Failed to authenticate credentials for reason: invalid token.",
  "success": false,
  "error": "asapi-auth-invalid"
}
`

What's the problem?

**Comment by afit** [comment]
Hi Francesco, thanks for opening a ticket. Unless you're already using a token, you'll need to sign up for one here: https://reincubate.com/ricloud-api/
