### ISSUE TITLE
Ios9.0 and above icloud backup 

### ISSUE THREAD

**Issue by prateek1108** [reincubate/ricloud#6]
Hi,
i want to list and download the backups in iCloud of ios version 9.0 and above. I tried this code to do so as this code is showing error while authenticating my icloud account. error its showing is error 14090086:SSL routines:SSL3_Get_Server_Certificate:Certificate verify failed.

**Comment by adriangonz** [comment]
Hi Prateek,

Looking at the error code, it looks like you may be using some sort of proxy. This may happen as well if you're connecting from an office (some monitoring systems rely on web proxies).

If that's the case, you can try:
- Disabling the proxy.
- Connecting from another computer.
- Connecting from another network (if you're connecting from your office).

To help you further, you can email our enterprise support team on enterprise@reincubate.com.

**Comment by prateek1108** [comment]
thanks for the quick reply. i am trying for sort and find the connection issue in my computer. But please do let me know is this code list listing and downloading icloud backup of ios 9 and above. 

thanks for helping and replying me.

**Comment by prateek1108** [comment]
hi,
I am able to run this code and list of ios9 icloud backup is listed but after that when i am selecting options to download error is coming.please help me out how i can download ios 9 backup.
![1234](https://cloud.githubusercontent.com/assets/5064077/15604033/a46b61da-241b-11e6-9c6d-1b29232664c8.png)

**Comment by adriangonz** [comment]
Hi Prateek,

We have just released an update to fix that bug. If you upgrade `ricloud` with `pip install --upgrade ricloud` it will work.

However, the default API Key doesn't have access to photo extraction, it only allows you to get the installed apps list. To try out more data types, please contact enterprise@reincubate.com.
