### ISSUE TITLE
Can not get devices after login

### ISSUE THREAD

**Issue by wiswashegrove** [reincubate/ricloud#8]
Hey,
I was just trying out this package, but didn't go well as expected.

I tried to login using `api.login(APPLE_ID, APPLE_PASSWORD)`
It successfully logged in. But `api.devices`  empty and my iCloud has one device attached.
I didn't overwrite anything in  `ricloud.ini`
Any clue what is going Wrong?

**Comment by afit** [comment]
Hi there, thanks for reaching out. I've replied to the email you sent in to support@reincubate.com. We'll get you up and running! :-)
