### ISSUE TITLE
Download snapchat file?

### ISSUE THREAD

**Issue by Jonovono** [reincubate/ricloud#9]
Hi, is this possible? I get a file_id for snapchat but when I download it it is showing as a text document.

Here is my code

    
     data_types = BackupClient.DATA_SNAPCHAT_MESSAGES

     data = api.backup_client.request_data(device, data_mask=data_types, since=since)

     i = 0

    for chat in data['snapchat_messages']:
        handle = chat['handle']
        attachments = chat['attachments']

        for attachment in attachments:
            file_id = attachment['file_id']
            filename = "file-%s" % str(i)
            with open(filename, 'wb') as out:
                api.backup_client.download_file(device, file_id, out)

            i = i + 1

**Comment by hlynursmari1** [comment]
Hi Jonovono,

It looks like your code should be recovering the Snapchat attachment files successfully, but the file’s mimetype is set incorrectly.

The `file_id` data that is returned from the Snapchat extractor does not have a declared file mimetype. Therefore, the files are likely not being saved in the correct format.

One method to determine the correct file extension to add to the attachment downloads is to use a package called [`python-magic`](https://github.com/ahupp/python-magic).

I’ve added a few lines to the code you posted which attempts to determine the filetype using this package.

```
import magic
import mimetypes
…

for chat in data['snapchat_messages']:
            handle = chat['handle']
            attachments = chat['attachments']

            for attachment in attachments:
                file_id = attachment['file_id']
                filename = "file-%s" % str(i)
                with open(filename, 'wb') as out:
                    api.backup_client.download_file(device_id, file_id, out)
                
                mimetype = magic.from_file(filename, mime=True)
                extension = mimetypes.guess_extension(mimetype)
                os.rename(filename, filename + extension)

                i += 1
```

This will output a variety of files, but mainly `zip` files, some `jpg` and some `mp4`. Once unzipped, the `zip` files contain a `media~` file, which we’ve found to be videos, and an `overlay~` file, which are images of the Snapchat overlays. You will need to add the appropriate extension (`mp4`) to the video files for them to be viewable.

There may also be some files which are identified as `ksh` format but these are simply `json` responses from the API declaring that it could not recover the targeted attachment.

I hope this helps.
Hlynur

**Comment by Jonovono** [comment]
@hlynursmari1 Awesome, thanks! This seems to work.
